### ISSUE TITLE
state of gcc7 on Mac?

### ISSUE THREAD

**Issue by djsutherland** [conda-forge/flann-feedstock#19]
Looks like the migration PR, https://github.com/conda-forge/flann-feedstock/pull/18, didn't add anything on Mac. Not sure what's going on there.

cc @conda-forge/core

**Comment by djsutherland** [comment]
Oh, it's because of:
```
    build:
        - {{ compiler('cxx') }}  # [not osx]
        - gcc     # [osx]
        - cmake
```
which is to be able to use OpenMP I think.

What's the state of OpenMP on Mac with the new compilers? I vaguely remember there still being something you had to do but can't find it immediately; will look into it later if someone doesn't just know.

I guess the answer to that determines what the right way to fix this is.

**Comment by ocefpaf** [comment]
> What's the state of OpenMP on Mac with the new compilers? I vaguely remember there still being something you had to do but can't find it immediately; will look into it later if someone doesn't just know.

I believe that @loriab or @isuruf may know the answer to that one.

**Comment by mariusvniekerk** [comment]
At the very least we need a new version without this selector

**Comment by jakirkham** [comment]
For these situations `defaults` uses `llvm-openmp` along with the new compilers. Would give that a try.
