### ISSUE TITLE
Update to latest flann

### ISSUE THREAD

**Issue by saedrna** [conda-forge/flann-feedstock#28]
- [ X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
Please update to the master branch of flann, because v1.9.1 of flann is not supporting c++17 (such as use of random_shuffle). It has been fixed already.

**Comment by wolfv** [comment]
@saedrna this is something you need to ask upstream about ... it looks like there is a fork.

**Comment by LunarLanding** [comment]
@wolfv could you help me understand? Do you mean nanoflann? It has a different API.
I see flann is pinned to 1.9.1 in conda-forge. So I guess you mean that flann's authors should fix their 1.9.1 version to run with c++17.
On the other hand, there seems to be no API changes going from 1.9.1 to 1.9.2. ([flann's changelog](https://github.com/flann-lib/flann/blob/master/ChangeLog)).

**Comment by traversaro** [comment]
Fixed by https://github.com/conda-forge/flann-feedstock/pull/41 .
