### ISSUE TITLE
package GCC needed on linux?

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/flann-feedstock#8]
I'm using `flann` in one project. It is the only dependency which pulls in `gcc`. I would avoid pulling in `gcc` for several reasons. Is there any need to use `gcc` here, or could we possibly drop it?

**Comment by jakevdp** [comment]
I believe it was required in order for OpenMP to work correctly. @jakirkham might know more about why it is included here.

**Comment by jakirkham** [comment]
Yes. That is the reason. What is this causing you issues with, @kmuehlbauer?

**Comment by kmuehlbauer** [comment]
Not yet, I'm still testing locally. But wanted to know why it is here, if I get some problems further down the road. I'll close this now. Thanks.
